baseurl: http://spacek.ca/
disablePathToLower: true
languageCode: en-us
title: development
params:
  Description: my ramblings
  links:
    Home: "/"
  twitter: https://twitter.com/nickspacek
  linkedin: https://ca.linkedin.com/in/nick-spacek-1b01b421
  facebook: https://www.facebook.com/nspacek
  github: https://github.com/nickspacek
