permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

title : development
tagline: projects and blog
author :
  name : Nick Spacek
  email : nick@spacek.ca
  github : nickspacek
  twitter : nickspacek

production_url : spacek.ca

JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : false

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : disqus
    disqus :
      short_name : nickspacekdevelopment

  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-10529487-2'

  sharing :
    provider : false
